import { getTrackingDetails } from "@lib/data/orders"
import { MapPin, Calendar, CheckCircleMiniSolid, FlyingBox, CircleInfoSolid, } from "@medusajs/icons"
import { StoreOrder } from "@medusajs/types"
import { clx } from "@medusajs/ui"

export default async function OrderTracking({ order }: { order: StoreOrder }) {
    // Get the latest fulfillment (by created_at)
    const latestFulfillment = order.fulfillments?.length
        ? [...order.fulfillments].sort(
            (a, b) =>
                new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
        )[0]
        : undefined
    // From that fulfillment, get the latest label (if any)
    const latestLabel =
        latestFulfillment?.labels && latestFulfillment.labels.length > 0
            ? latestFulfillment.labels[latestFulfillment.labels.length - 1]
            : undefined

    const awb = latestLabel?.tracking_number
    //   const trackingUrl = latestLabel?.tracking_url

    const rawData = await getTrackingDetails(awb)
    const data = rawData?.tracking_data

    if (!data || !data.shipment_track || data.track_status === 0) {
        return (
            <div className="bg-white p-6 border rounded-xl shadow-sm border-ui-border-base mb-8">
                <div className="flex items-center gap-x-2 text-ui-fg-base mb-2">
                    <FlyingBox className="text-ui-fg-subtle" />
                    <h3 className="text-base-semi font-semibold">Shipment Status</h3>
                </div>
                <p className="text-ui-fg-subtle text-sm italic">
                    Shipment information is being generated by the courier.
                </p>
            </div>
        )
    }

    const info = data.shipment_track[0]
    // Reverse activities only if the first one is the oldest, to ensure newest is at top
    const activities = [...(data.shipment_track_activities || [])]
    const isDelivered = info?.current_status?.toLowerCase() === "delivered"

    // Late Day Logic
    const today = new Date()
    const etdDate = data.etd ? new Date(data.etd) : null
    const isLate = etdDate && today > etdDate && !isDelivered

    return (
        <div className="bg-white border rounded-xl overflow-hidden shadow-sm border-ui-border-base mb-8">
            {/* 1. Header with Status Badge */}
            <div className="bg-ui-bg-subtle p-6 border-b border-ui-border-base flex flex-col sm:flex-row justify-between gap-4">
                <div>
                    <h3 className="text-lg-semi font-bold flex items-center gap-2 text-ui-fg-base">
                        Package Journey {isDelivered && <CheckCircleMiniSolid className="text-green-500" />}
                    </h3>
                    <p className="text-xs text-ui-fg-muted uppercase tracking-wider font-medium">
                        {info?.courier_name || "Courier"} • AWB {info?.awb_code || awb}
                    </p>
                </div>
                <div className="sm:text-right">
                    <span className={clx(
                        "inline-flex px-3 py-1 rounded-full text-xs font-bold uppercase tracking-widest shadow-sm",
                        isDelivered ? "bg-green-100 text-green-700" : "bg-blue-600 text-white"
                    )}>
                        {info?.current_status || "In Transit"}
                    </span>
                </div>
            </div>

            {/* 2. Late Delivery Alert */}
            {isLate && (
                <div className="bg-orange-50 border-b border-orange-100 p-4 flex items-center gap-3">
                    <CircleInfoSolid className="text-orange-600" />
                    <p className="text-sm text-orange-800 font-medium">
                        Your delivery is taking a bit longer than expected. We're working with the courier to get it to you as soon as possible.
                    </p>
                </div>
            )}

            <div className="p-6 grid grid-cols-1 md:grid-cols-2 gap-10">
                {/* 3. Summary Section */}
                <div className="space-y-6">
                    <div>
                        <div className="flex gap-4 mb-6">
                            <div className={clx(
                                "p-2 rounded-lg h-fit",
                                isLate ? "bg-orange-100" : "bg-blue-50"
                            )}>
                                <Calendar className={isLate ? "text-orange-600" : "text-blue-600"} />
                            </div>
                            <div>
                                <p className="text-xs text-ui-fg-muted uppercase font-bold tracking-tight">
                                    {isDelivered ? "Delivered On" : "Est. Delivery"}
                                </p>
                                <p className={clx(
                                    "text-base-semi font-semibold",
                                    isLate ? "text-orange-700" : "text-ui-fg-base"
                                )}>
                                    {new Date(isDelivered ? info.delivered_date! : data.etd).toLocaleDateString('en-IN', {
                                        weekday: 'long',
                                        month: 'short',
                                        day: 'numeric'
                                    })}
                                </p>
                            </div>
                        </div>

                        <div className="flex gap-4">
                            <div className="p-2 bg-gray-50 rounded-lg h-fit text-ui-fg-subtle">
                                <MapPin />
                            </div>
                            <div>
                                <p className="text-xs text-ui-fg-muted uppercase font-bold tracking-tight">Destination</p>
                                <p className="text-base-semi font-semibold text-ui-fg-base">
                                    {info?.destination || "Shipping Address"}
                                </p>
                            </div>
                        </div>
                    </div>

                    {/* {data.track_url && (
                        <a
                            href={data.track_url}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex w-full items-center justify-center rounded-md border border-ui-border-base py-3 px-4 text-sm font-medium hover:bg-gray-50 transition-all shadow-sm text-ui-fg-base bg-white"
                        >
                            External Tracking Link
                        </a>
                    )} */}
                </div>

                {/* 4. Timeline Section */}
                <div className="relative border-l-2 border-gray-100 ml-2 pl-8 space-y-8">
                    {activities.length > 0 ? (
                        activities.slice(0, 6).map((act: any, i: number) => (
                            <div key={i} className="relative">
                                {/* Dot Indicator */}
                                <span className={clx(
                                    "absolute -left-[41px] w-4 h-4 rounded-full ring-4 ring-white z-10",
                                    i === 0 ? (isDelivered ? "bg-green-500" : "bg-blue-600") : "bg-gray-200"
                                )} />

                                {/* Pulse Effect for newest active status */}
                                {i === 0 && !isDelivered && (
                                    <span className="absolute -left-[41px] w-4 h-4 rounded-full bg-blue-600 animate-ping opacity-25" />
                                )}

                                <div className="flex flex-col">
                                    <p className={clx(
                                        "text-sm font-bold leading-tight",
                                        i === 0 ? "text-ui-fg-base" : "text-ui-fg-subtle"
                                    )}>
                                        {act.activity}
                                    </p>
                                    <p className="text-[11px] text-ui-fg-muted mt-1 font-medium">
                                        {new Date(act.date).toLocaleString('en-IN', {
                                            dateStyle: 'medium',
                                            timeStyle: 'short'
                                        })}
                                        {act.location && ` • ${act.location}`}
                                    </p>
                                </div>
                            </div>
                        ))
                    ) : (
                        <p className="text-sm text-ui-fg-muted italic">No movement scans recorded yet.</p>
                    )}
                </div>
            </div>
        </div>
    )
}